version: "3"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'ubnt'
      MYSQL_ROOT_PASSWORD: 'ubnt'
    ports:
      - 3306:3306
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql